# Generated by Django 3.1 on 2020-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='phone',
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.CharField(default='', max_length=4000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email филиала'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='website',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сайт филиала'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='body',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Текст слайда'),
        ),
    ]
