# Generated by Django 3.1 on 2020-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_auto_20200825_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideritem',
            options={'ordering': ('-sorting',), 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AddField(
            model_name='slideritem',
            name='sorting',
            field=models.PositiveIntegerField(default=0, help_text='Слайды будут расположены согласно данной сортировке', verbose_name='Сортировка'),
        ),
    ]
