# Generated by Django 3.1 on 2020-09-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_auto_20200825_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='geocode_lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='geocode_lon',
        ),
    ]
