# Generated by Django 3.1 on 2020-09-10 15:13

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0005_auto_20200910_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniSliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Цитата')),
                ('author', models.CharField(max_length=100, verbose_name='Автор цитаты')),
                ('description', models.CharField(max_length=400, verbose_name='Краткая информация об авторе цитаты')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='slider-mini/', verbose_name='Фото автора цитаты')),
                ('active', models.BooleanField(default=True, help_text='Неактивные цитаты не будут отображаться на главной странице', verbose_name='Активен')),
                ('crop', image_cropping.fields.ImageRatioField('image', '106x118', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения')),
                ('sorting', models.PositiveIntegerField(default=0, help_text='Цитаты будут расположены согласно данной сортировке', verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ('-sorting',),
            },
        ),
    ]
