# Generated by Django 3.1 on 2020-09-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0006_minislideritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minislideritem',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор цитаты'),
        ),
        migrations.AlterField(
            model_name='minislideritem',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Краткая информация об авторе цитаты'),
        ),
        migrations.AlterField(
            model_name='minislideritem',
            name='image',
            field=models.ImageField(blank=True, help_text='Возможность обрезки появится после сохранения', null=True, upload_to='slider-mini/', verbose_name='Фото автора цитаты'),
        ),
        migrations.AlterField(
            model_name='minislideritem',
            name='quote',
            field=models.TextField(default='', max_length=1000, verbose_name='Цитата'),
            preserve_default=False,
        ),
    ]
