# Generated by Django 3.1 on 2020-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0007_auto_20200910_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('name',), 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='no',
        ),
        migrations.AlterField(
            model_name='branch',
            name='custom_metro_station',
            field=models.CharField(blank=True, help_text='Будет использоваться вместо выбранного из списка, если указано', max_length=400, null=True, verbose_name='Метро (ручной ввод)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='D', help_text='Необязательное поле. При отсуствии названия будет выводиться номер филиала', max_length=200, verbose_name='Название филиала'),
            preserve_default=False,
        ),
    ]
