# Generated by Django 3.1 on 2020-09-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0009_auto_20200910_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='custom_metro_station',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы отображать выбранную из списка станцию метро', max_length=400, null=True, verbose_name='Метро (ручной ввод)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название филиала'),
        ),
    ]
