# Generated by Django 3.1 on 2020-09-11 18:49

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0011_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': [django.db.models.functions.text.Length('name'), 'name'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
    ]
