# Generated by Django 3.1 on 2020-09-14 12:42

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0012_auto_20200911_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': [django.db.models.functions.text.Left('name', 1), django.db.models.functions.text.Length('name'), 'name'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
    ]
