# Generated by Django 3.1 on 2020-09-16 13:50

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0013_auto_20200914_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minislideritem',
            name='crop',
        ),
        migrations.AddField(
            model_name='minislideritem',
            name='crop_mini',
            field=image_cropping.fields.ImageRatioField('image', '106x118', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения (маленькие экраны)'),
        ),
        migrations.AddField(
            model_name='minislideritem',
            name='crop_normal',
            field=image_cropping.fields.ImageRatioField('image', '200x223', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения (большие экраны)'),
        ),
    ]
