# Generated by Django 3.1 on 2020-09-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0015_auto_20200916_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200, unique=True, verbose_name='Название шаблона')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_postfix', models.BooleanField(default=True, verbose_name='Включить постфикс (дополнение к заголовку с конца)')),
                ('meta_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание (мета-тег)')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ключевые слова (мета-тег)')),
            ],
            options={
                'verbose_name': 'CEO настройки страницы',
                'verbose_name_plural': 'CEO настройки страниц',
            },
        ),
    ]
