# Generated by Django 3.1 on 2020-09-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0016_ceosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceosettings',
            name='has_custom_title',
            field=models.BooleanField(default=False, verbose_name='Имеет динамический (создаётся согласно контенту) заголовок'),
        ),
        migrations.AlterField(
            model_name='ceosettings',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать информацию из шаблона base.html', max_length=1000, null=True, verbose_name='Описание (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='ceosettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать информацию из шаблона base.html', max_length=500, null=True, verbose_name='Ключевые слова (мета-тег)'),
        ),
        migrations.AlterField(
            model_name='ceosettings',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Оставьте поле пустым, чтобы использовать информацию из шаблона base.html', max_length=200, verbose_name='Заголовок'),
        ),
    ]
