# Generated by Django 3.1 on 2020-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0017_auto_20200917_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceosettings',
            name='meta_robots',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать информацию из шаблона base.html', max_length=500, null=True, verbose_name='Robots (мета-тег)'),
        ),
    ]
