# Generated by Django 3.1 on 2020-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sorting',
            field=models.CharField(default='zz', help_text='Подразделы будут появляться в списке раздела, согласно данной сортировке (по алфавиту, в порядке убывания)', max_length=5, verbose_name='Сортировка'),
        ),
    ]
