# Generated by Django 3.1 on 2020-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0005_auto_20200910_1734'),
        ('users', '0002_auto_20200825_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='branch',
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.ManyToManyField(to='other.Branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='merits',
            field=models.TextField(blank=True, null=True, verbose_name='Заслуги'),
        ),
    ]
