# Generated by Django 3.1 on 2020-09-11 09:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0011_settings'),
        ('users', '0003_auto_20200910_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.ManyToManyField(blank=True, null=True, to='other.Branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(None, 'Не указано'), ('head-president', 'Президент клуба'), ('vice-president', 'Вице-президент клуба'), ('judiciary', 'Судейский корпус'), ('single-coach', 'Инструктор'), ('coach-committee', 'Тренерский комитет'), ('methodical-certification-committee', 'Методический и аттестационный комитет'), ('physical-mass-committee', 'Физкультурно-массовый комитет'), ('administration', 'Администрация'), ('parental-committee', 'Родительский комитет')], max_length=300, null=True, verbose_name='Должности'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Короткое описание'),
        ),
    ]
