# Generated by Django 3.1 on 2020-08-24 19:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название подраздела')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL подраздела')),
                ('active', models.BooleanField(default=True, help_text='Неактивные страницы не будут отображаться в списке подразделов', verbose_name='Страница активна')),
                ('custom_database_query', models.BooleanField(default=False, help_text='Крайне не рекомендуется удалять страницы с уникальным запросом в базу данных', verbose_name='Имеет уникальный запрос в базу данных')),
                ('image', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='static-pages/about/', verbose_name='Изображение статьи')),
                ('content', models.TextField(help_text='Перетащите изображение в редактор, чтобы загрузить его на сервер', verbose_name='Контент страницы')),
                ('sorting', models.CharField(default='z', help_text='Подразделы будут появляться в списке раздела согласно данной сортировке (по алфавиту, в порядке убывания)', max_length=5, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Страница раздела "О клубе"',
                'verbose_name_plural': 'Страницы раздела "О клубе"',
            },
        ),
        migrations.CreateModel(
            name='KarateStaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название подраздела')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL подраздела')),
                ('active', models.BooleanField(default=True, help_text='Неактивные страницы не будут отображаться в списке подразделов', verbose_name='Страница активна')),
                ('custom_database_query', models.BooleanField(default=False, help_text='Крайне не рекомендуется удалять страницы с уникальным запросом в базу данных', verbose_name='Имеет уникальный запрос в базу данных')),
                ('image', models.ImageField(blank=True, help_text='Возможность обрезки появится после сохранения', null=True, upload_to='static-pages/karate/', verbose_name='Изображение статьи')),
                ('content', models.TextField(help_text='Перетащите изображение в редактор, чтобы загрузить его на сервер', verbose_name='Контент страницы')),
                ('sorting', models.CharField(default='z', help_text='Подразделы будут появляться в списке раздела согласно данной сортировке (по алфавиту, в порядке убывания)', max_length=5, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Страница раздела "Карате"',
                'verbose_name_plural': 'Страницы раздела "Карате"',
            },
        ),
        migrations.CreateModel(
            name='TaekwondoStaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название подраздела')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True, verbose_name='URL подраздела')),
                ('active', models.BooleanField(default=True, help_text='Неактивные страницы не будут отображаться в списке подразделов', verbose_name='Страница активна')),
                ('custom_database_query', models.BooleanField(default=False, help_text='Крайне не рекомендуется удалять страницы с уникальным запросом в базу данных', verbose_name='Имеет уникальный запрос в базу данных')),
                ('image', models.ImageField(blank=True, help_text='Возможность обрезки появится после сохранения', null=True, upload_to='static-pages/taekwondo/', verbose_name='Изображение статьи')),
                ('content', models.TextField(help_text='Перетащите изображение в редактор, чтобы загрузить его на сервер', verbose_name='Контент страницы')),
                ('sorting', models.CharField(default='z', help_text='Подразделы будут появляться в списке раздела согласно данной сортировке (по алфавиту, в порядке убывания)', max_length=5, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Страница раздела "Тхэквондо"',
                'verbose_name_plural': 'Страницы раздела "Тхэквондо"',
            },
        ),
    ]
