# Generated by Django 3.1 on 2020-08-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstaticpage',
            name='additional_content_left',
            field=models.TextField(blank=True, help_text='Дополнительный контент расположен под списком подразделов (слева)', null=True, verbose_name='Дополнительный контент страницы (левая часть)'),
        ),
        migrations.AddField(
            model_name='aboutstaticpage',
            name='additional_content_right',
            field=models.TextField(blank=True, help_text='Дополнительный контент расположен прямо под основным контентом (справа)', null=True, verbose_name='Дополнительный контент страницы (правая часть)'),
        ),
        migrations.AlterField(
            model_name='aboutstaticpage',
            name='content',
            field=models.TextField(blank=True, help_text='Перетащите изображение в редактор, чтобы загрузить его на сервер', null=True, verbose_name='Контент страницы'),
        ),
    ]
