# Generated by Django 3.1 on 2020-08-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_auto_20200825_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstaticpage',
            name='sorting',
            field=models.CharField(default='zz', help_text='Подразделы будут появляться в списке раздела согласно данной сортировке (по алфавиту, в порядке убывания)', max_length=5, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='karatestaticpage',
            name='sorting',
            field=models.CharField(default='zz', help_text='Подразделы будут появляться в списке раздела согласно данной сортировке (по алфавиту, в порядке убывания)', max_length=5, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='taekwondostaticpage',
            name='sorting',
            field=models.CharField(default='zz', help_text='Подразделы будут появляться в списке раздела согласно данной сортировке (по алфавиту, в порядке убывания)', max_length=5, verbose_name='Сортировка'),
        ),
    ]
