# Generated by Django 3.1 on 2020-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0003_auto_20200825_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutstaticpage',
            options={'ordering': ('sorting',), 'verbose_name': 'Страница раздела "О клубе"', 'verbose_name_plural': 'Страницы раздела "О клубе"'},
        ),
        migrations.AlterModelOptions(
            name='karatestaticpage',
            options={'ordering': ('sorting',), 'verbose_name': 'Страница раздела "Карате"', 'verbose_name_plural': 'Страницы раздела "Карате"'},
        ),
        migrations.AlterModelOptions(
            name='taekwondostaticpage',
            options={'ordering': ('sorting',), 'verbose_name': 'Страница раздела "Тхэквондо"', 'verbose_name_plural': 'Страницы раздела "Тхэквондо"'},
        ),
        migrations.AlterField(
            model_name='aboutstaticpage',
            name='sorting',
            field=models.PositiveIntegerField(default=0, help_text='Подразделы будут появляться в списке раздела согласно данной сортировке', verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='karatestaticpage',
            name='sorting',
            field=models.PositiveIntegerField(default=0, help_text='Подразделы будут появляться в списке раздела согласно данной сортировке', verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='taekwondostaticpage',
            name='sorting',
            field=models.PositiveIntegerField(default=0, help_text='Подразделы будут появляться в списке раздела согласно данной сортировке', verbose_name='Сортировка'),
        ),
    ]
