# Generated by Django 3.1 on 2020-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0007_auto_20200910_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstaticpage',
            name='meta_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать метатег description базового шаблона', max_length=4000, null=True, verbose_name='Содержимое тега <meta name="description">'),
        ),
        migrations.AddField(
            model_name='aboutstaticpage',
            name='title_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать название подраздела как заголовок страницы', max_length=300, null=True, verbose_name='Содержимое тега <title>'),
        ),
        migrations.AddField(
            model_name='karatestaticpage',
            name='meta_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать метатег description базового шаблона', max_length=4000, null=True, verbose_name='Содержимое тега <meta name="description">'),
        ),
        migrations.AddField(
            model_name='karatestaticpage',
            name='title_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать название подраздела как заголовок страницы', max_length=300, null=True, verbose_name='Содержимое тега <title>'),
        ),
        migrations.AddField(
            model_name='taekwondostaticpage',
            name='meta_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать метатег description базового шаблона', max_length=4000, null=True, verbose_name='Контент тега <meta name="description">'),
        ),
        migrations.AddField(
            model_name='taekwondostaticpage',
            name='title_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать название подраздела как заголовок страницы', max_length=300, null=True, verbose_name='Содержимое тега <title>'),
        ),
    ]
