# Generated by Django 3.1 on 2020-09-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0008_auto_20200911_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstaticpage',
            name='meta_keywords_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать метатег keywords базового шаблона', max_length=2000, null=True, verbose_name='Содержимое тега <meta name="keywords">'),
        ),
        migrations.AddField(
            model_name='karatestaticpage',
            name='meta_keywords_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать метатег keywords базового шаблона', max_length=2000, null=True, verbose_name='Содержимое тега <meta name="keywords">'),
        ),
        migrations.AddField(
            model_name='taekwondostaticpage',
            name='meta_keywords_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать метатег keywords базового шаблона', max_length=2000, null=True, verbose_name='Содержимое тега <meta name="keywords">'),
        ),
        migrations.AlterField(
            model_name='aboutstaticpage',
            name='meta_tag',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать метатег description базового шаблона', max_length=2000, null=True, verbose_name='Содержимое тега <meta name="description">'),
        ),
    ]
