# Generated by Django 3.1 on 2020-08-26 13:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200826_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=autoslug.fields.AutoSlugField(default=123, editable=True, populate_from='title', unique=True, verbose_name='URL статьи'),
            preserve_default=False,
        ),
    ]
