# Generated by Django 3.1 on 2020-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='associations',
            field=models.ManyToManyField(blank=True, to='news.ArticleCategory', verbose_name='Категории'),
        ),
    ]
