# Generated by Django 3.1 on 2020-09-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200910_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать первые 250 знаков статьи', max_length=1000, null=True, verbose_name='Описание (мета-тег)'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, чтобы использовать информацию из шаблона news.html', max_length=1000, null=True, verbose_name='Описание (мета-тег)'),
        ),
    ]
