# Generated by Django 3.1 on 2020-08-24 19:59

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import ramenki.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('url', autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True, validators=[ramenki.utils.category_url_validator], verbose_name='URL категории')),
                ('active', models.BooleanField(default=True, help_text='Неактивные категории не будут отображаться в списке категорий', verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Категория медиа',
                'verbose_name_plural': 'Категории медиа',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название фото')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Файл')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название видео')),
                ('description', models.CharField(blank=True, help_text='Необязательно', max_length=5000, null=True, verbose_name='Описание видео')),
                ('link', models.CharField(help_text='Ссылку можно получить нажав "Поделиться" под видео', max_length=200, verbose_name='Ссылка на видео')),
                ('thumbnail', models.ImageField(blank=True, help_text='Возможность обрезки появится после сохранения', null=True, upload_to='video-thumbnails/', verbose_name='Обложка видео')),
                ('crop', image_cropping.fields.ImageRatioField('thumbnail', '344x276', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для обложки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mediacontent.mediacategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название галереи')),
                ('thumbnail', models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='photo-galleries/djangodbmodelsfieldscharfield', verbose_name='Обложка альбома')),
                ('crop', image_cropping.fields.ImageRatioField('thumbnail', '344x276', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для обложки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mediacontent.mediacategory', verbose_name='Категории')),
                ('photos', models.ManyToManyField(to='mediacontent.Photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото-галерея',
                'verbose_name_plural': 'Фото-галереи',
            },
        ),
    ]
