# Generated by Django 3.1 on 2020-09-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0002_auto_20200910_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mediacontent.mediacategory', verbose_name='Категории'),
        ),
    ]
