# Generated by Django 3.1 on 2020-09-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0004_auto_20200914_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='thumbnail',
            field=models.ImageField(help_text='Возможность обрезки появится после сохранения', upload_to='photo-galleries/djangodbmodelsfieldscharfield', verbose_name='Обложка галереи'),
        ),
    ]
