# Generated by Django 3.1 on 2020-09-16 17:00

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mediacontent', '0008_auto_20200916_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='use_raw_thumbnail',
            field=models.BooleanField(default=True, verbose_name='Использовать оригинальное фото обложки (без обрезки)'),
        ),
        migrations.AddField(
            model_name='video',
            name='use_raw_thumbnail',
            field=models.BooleanField(default=True, verbose_name='Использовать оригинальное фото обложки (без обрезки)'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='crop',
            field=image_cropping.fields.ImageRatioField('thumbnail', '448x276', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для обложки'),
        ),
        migrations.AlterField(
            model_name='video',
            name='crop',
            field=image_cropping.fields.ImageRatioField('thumbnail', '448x276', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Обрезка изображения для обложки'),
        ),
    ]
